language: php

php:
  - 7.0
  - 7.1

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
    - make tests
